name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Resolve deps
      run: go mod tidy
      
    - name: Build
      run: go build -v ./...
      
  buildImage:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     
     - name: Get version
       id: get_version
       run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
     
     - name: Build docker image
       run: docker build . -t standardcore/osssync:${{ steps.get_version.outputs.VERSION }}
       
  publish:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     
     - name: Docker login
       run: echo ${{ secrets.DOCKER_PASSWORD }}  | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
       
     - name: Docker push
       run: docker push standardcore/osssync:${{ steps.get_version.outputs.VERSION }}
